<a href="https://colab.research.google.com/github/thucuyen127/pycharm/blob/master/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

def taomatran(n): #Hàm tạo ma trận n hàng n cột
  a = np.random.randint(-10,10,(n,n))
  return a
m=int(input('m = '))
a = taomatran(m)
b = taomatran(m)
print('A = \n',a)
print('B = \n',b)
print('A + B = \n',a + b)
print('A - B = \n',a - b)
print('A * B = \n',a @ b)
print('A / B = \n',a  @ np.linalg.matrix_power(b, -1))
print('A * 5 = \n',a * 5)
print('A / 5 = \n',a / 5)
print('ma tran chuyen vi cua A:\n',np.transpose(a))


m = 3
A = 
 [[-8  6 -1]
 [-3  3 -3]
 [-2  0 -4]]
B = 
 [[  4  -6  -9]
 [  0   4 -10]
 [  7   8  -3]]
A + B = 
 [[ -4   0 -10]
 [ -3   7 -13]
 [  5   8  -7]]
A - B = 
 [[-12  12   8]
 [ -3  -1   7]
 [ -9  -8  -1]]
A * B = 
 [[-39  64  15]
 [-33   6   6]
 [-36 -20  30]]
A / B = 
 [[-0.99152542  1.16525424 -0.57627119]
 [-0.34957627  0.68326271 -0.22881356]
 [-0.02542373  0.50423729 -0.27118644]]
A * 5 = 
 [[-40  30  -5]
 [-15  15 -15]
 [-10   0 -20]]
A / 5 = 
 [[-1.6  1.2 -0.2]
 [-0.6  0.6 -0.6]
 [-0.4  0.  -0.8]]
ma tran chuyen vi cua A:
 [[-8 -3 -2]
 [ 6  3  0]
 [-1 -3 -4]]
